---
- name: Management a Directory Server
  hosts: ldap-server
  gather_facts: false
  vars:
    userlogin: cn=angelguzman,ou=people,dc=pruebas,dc=argl,dc=io
  tasks:  
    - name: copy user to ldap
      template:
        src: add-user.j2
        dest: /tmp/add-user.ldif
    - name: add user to ldap
      ansible.builtin.command: ldapadd -x  -D  {{ userlogin  }} -w {{ passlogin }}  -f /tmp/add-user.ldif
    - name: delete template
      ansible.builtin.command: rm -rf add-user.ldif  