---
- name: Create backup and copy 
  hosts: database
  gather_facts: yes
  tasks:
    
    - name: Create directory ansible
      ansible.builtin.file:
        path: /home/oracle/ansible
        state: directory
    
    - name: Run backup shell
      ansible.builtin.shell: /home/oracle/backup.sh >> somelog.txt

 
    - name: Send files
      shell: rsync -avz  /backup/oracle/rman/ admin@{{ host_dest }}:/home/admin/backup
  
